kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
kubeadmConfigPatches:
- |
  apiVersion: kind.x-k8s.io/v1alpha4
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  #imageRepository: registry.aliyuncs.com/google_containers 
  #nodeRegistration: 
  #  kubeletExtraArgs: 
  #    pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.1 
- |
  apiVersion: kind.x-k8s.io/v1alpha4
  kind: InitConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  #imageRepository: registry.aliyuncs.com/google_containers
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker