apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: hello
          imagePullPolicy: "IfNotPresent"
          name: hello
          command:
            - "./server"
          ports:
            - containerPort: 8080
              protocol: TCP
